[package]
name = "swarm-cli"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[[bin]]
name = "swarm-cli"
path = "src/main.rs"

[dependencies]
swarm-core = { path = "../swarm-core" }
clap.workspace = true
indicatif.workspace = true
serde.workspace = true
serde_json.workspace = true
csv.workspace = true
rand.workspace = true
rand_distr.workspace = true
